Updated Jetty to 12.0.9.
cometd/cometd pull request #1739
Opened 2024-05-03 21:31 UTC by sbordet

Updated CometD to new behavior of Jetty 12.0.9 where stopping the ServerConnector triggers the failure of suspended requests.

2024-05-06 06:58 UTC, lorban requested changes

2024-05-06 06:58 UTC, lorban commented on cometd-java/cometd-java-server/cometd-java-server-http/cometd-java-server-http-tests/src/test/java/org/cometd/server/http/ext/AcknowledgeExtensionTest.java
> +        // TODO: fix comments above
It looks like the right moment to fix the comments above.

2024-05-06 06:58 UTC, lorban commented on cometd-java/cometd-java-server/cometd-java-server-http/cometd-java-server-http-jakarta/src/main/java/org/cometd/server/http/jakarta/JakartaCometDRequest.java
> +    private record FailureListener(Consumer<Throwable> handler) implements AsyncListener {
I'm nitpicking here, but a `record` doesn't look like the best choice for this purpose.

2024-05-06 06:58 UTC, lorban commented on cometd-java/cometd-java-server/cometd-java-server-common/src/main/java/org/cometd/server/http/AbstractHttpTransport.java
> +                            request.addFailureHandler(failure -> scheduler.cancel());
Why not `session.setScheduler(null)`?

2024-05-15 08:11 UTC, lorban requested changes
Mostly good, only my previous comments still remain unaddressed.

2024-05-15 12:28 UTC, sbordet commented on cometd-java/cometd-java-server/cometd-java-server-common/src/main/java/org/cometd/server/http/AbstractHttpTransport.java
> +                            request.addFailureHandler(failure -> scheduler.cancel());
Because now we can pass the specific failure to the scheduler.

2024-05-15 12:35 UTC, lorban approved these changes

2024-05-15 15:26 UTC, merged